#if !defined(AFX_MDCCOMBO_H__DB076796_D2CD_4CA2_B02F_E1EE6293D1EB__INCLUDED_)
#define AFX_MDCCOMBO_H__DB076796_D2CD_4CA2_B02F_E1EE6293D1EB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CMdcCombo wrapper class

class CMdcCombo : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMdcCombo)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8bd21d30, 0xec42, 0x11ce, { 0x9e, 0xd, 0x0, 0xaa, 0x0, 0x60, 0x2, 0xf3 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetAutoSize(BOOL bNewValue);
	BOOL GetAutoSize();
	void SetAutoTab(BOOL bNewValue);
	BOOL GetAutoTab();
	void SetAutoWordSelect(BOOL bNewValue);
	BOOL GetAutoWordSelect();
	void SetBackColor(long nNewValue);
	long GetBackColor();
	void SetBackStyle(long nNewValue);
	long GetBackStyle();
	void SetBorderColor(long nNewValue);
	long GetBorderColor();
	void SetBorderStyle(long nNewValue);
	long GetBorderStyle();
	void SetBoundColumn(VARIANT* newValue);
	VARIANT GetBoundColumn();
	BOOL GetCanPaste();
	void SetColumnCount(long nNewValue);
	long GetColumnCount();
	void SetColumnHeads(BOOL bNewValue);
	BOOL GetColumnHeads();
	void SetColumnWidths(LPCTSTR lpszNewValue);
	CString GetColumnWidths();
	long GetCurTargetX();
	void SetCurX(long nNewValue);
	long GetCurX();
	void SetDropButtonStyle(long nNewValue);
	long GetDropButtonStyle();
	void SetEnabled(BOOL bNewValue);
	BOOL GetEnabled();
	void SetRefFont(LPDISPATCH newValue);
	COleFont GetFont();
	void SetForeColor(long nNewValue);
	long GetForeColor();
	void SetHideSelection(BOOL bNewValue);
	BOOL GetHideSelection();
	long GetLineCount();
	long GetListCount();
	void SetListIndex(VARIANT* newValue);
	VARIANT GetListIndex();
	void SetListRows(long nNewValue);
	long GetListRows();
	void SetListStyle(long nNewValue);
	long GetListStyle();
	void SetListWidth(VARIANT* newValue);
	VARIANT GetListWidth();
	void SetLocked(BOOL bNewValue);
	BOOL GetLocked();
	void SetMatchEntry(long nNewValue);
	long GetMatchEntry();
	BOOL GetMatchFound();
	void SetMatchRequired(BOOL bNewValue);
	BOOL GetMatchRequired();
	void SetMaxLength(long nNewValue);
	long GetMaxLength();
	void SetMouseIcon(LPDISPATCH newValue);
	void SetRefMouseIcon(LPDISPATCH newValue);
	CPicture GetMouseIcon();
	void SetMousePointer(long nNewValue);
	long GetMousePointer();
	void SetSelectionMargin(BOOL bNewValue);
	BOOL GetSelectionMargin();
	void SetSelLength(long nNewValue);
	long GetSelLength();
	void SetSelStart(long nNewValue);
	long GetSelStart();
	void SetSelText(LPCTSTR lpszNewValue);
	CString GetSelText();
	void SetShowDropButtonWhen(long nNewValue);
	long GetShowDropButtonWhen();
	void SetSpecialEffect(long nNewValue);
	long GetSpecialEffect();
	void SetStyle(long nNewValue);
	long GetStyle();
	void SetText(LPCTSTR lpszNewValue);
	CString GetText();
	void SetTextAlign(long nNewValue);
	long GetTextAlign();
	void SetTextColumn(VARIANT* newValue);
	VARIANT GetTextColumn();
	long GetTextLength();
	void SetTopIndex(VARIANT* newValue);
	VARIANT GetTopIndex();
	void SetValue(VARIANT* newValue);
	VARIANT GetValue();
	VARIANT GetColumn(VARIANT* pvargColumn, VARIANT* pvargIndex);
	void SetColumn(VARIANT* pvargColumn, VARIANT* pvargIndex, VARIANT* newValue);
	VARIANT GetList(VARIANT* pvargIndex, VARIANT* pvargColumn);
	void SetList(VARIANT* pvargIndex, VARIANT* pvargColumn, VARIANT* newValue);
	void AddItem(VARIANT* pvargItem, VARIANT* pvargIndex);
	void Clear();
	void DropDown();
	void RemoveItem(VARIANT* pvargIndex);
	void Copy();
	void Cut();
	void Paste();
	void SetIMEMode(long nNewValue);
	long GetIMEMode();
	void SetEnterFieldBehavior(long nNewValue);
	long GetEnterFieldBehavior();
	void SetDragBehavior(long nNewValue);
	long GetDragBehavior();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MDCCOMBO_H__DB076796_D2CD_4CA2_B02F_E1EE6293D1EB__INCLUDED_)
